version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /root/bmw-momentum/scripts/cookies_towbook.json:/app/scripts/cookies_towbook.json
    restart: unless-stopped

# Optional: If you want to add more services (like a database), you can do that here.
